"""DDI Converter - Template for ddi.sh argument conversion layer.

ddi.sh is generated by the upstream flow and currently invokes:
    /path/to/main/program.pl -arg_a value_a -arg_b value_b ...

This module converts those legacy arguments into RepackConfig
for the new Repack engine.

TEMPLATE: Fill in the argument mappings based on your internal spec.
The structure is here; you just need to map old args to new config fields.
"""

import logging
import os
import re
import shlex
import subprocess
from typing import Any, Dict, List, Optional, Tuple

from repack.config import RepackConfig
from repack.core.spec import SpecCollection

logger = logging.getLogger(__name__)


class DDIConverter:
    """Converts ddi.sh arguments to RepackConfig.

    Usage:
        converter = DDIConverter()
        config = converter.from_ddi_sh("/path/to/ddi.sh")
        # Then pass config to RepackEngine
    """

    # ================================================================
    # TEMPLATE: Map legacy arg names to RepackConfig fields.
    #
    # Format: { "-legacy_flag": "config_field_name" }
    #
    # For simple 1:1 mappings where the value can be used directly.
    # For complex transformations, add handling in _transform_value().
    # ================================================================
    ARG_MAP: Dict[str, str] = {
        # Example mappings (replace with actual legacy flags):
        # "-old_name": "old_name",
        # "-old_ver": "old_ver",
        # "-new_name": "new_name",
        # "-new_ver": "new_ver",
        # "-source_lib": "source_lib",
        # "-out_dir": "output_root",
        # "-pvt_list": "pvts",        # needs _transform_value
        # "-cell_list": "cells",      # needs _transform_value
        # "-upload_path": "upload_dest",
    }

    # Flags that don't take a value (presence = True).
    # -gen_{kit} flags are boolean: presence means "generate this kit".
    # They are collected separately and used to determine which kits
    # register_kits() returns. They do NOT go into RepackConfig.
    BOOLEAN_FLAGS: set = {
        # "-gen_liberty",
        # "-gen_lef",
        # "-gen_timing_db",
    }

    # Prefix for gen flags. Matched flags are collected into gen_kits set.
    GEN_FLAG_PREFIX: str = "-gen_"

    def from_ddi_sh(self, ddi_sh_path: str) -> RepackConfig:
        """Parse a ddi.sh file and convert to RepackConfig.

        Args:
            ddi_sh_path: Path to the ddi.sh script.

        Returns:
            Populated RepackConfig.
        """
        raw_args = self._extract_args(ddi_sh_path)
        logger.info("Extracted %d arguments from %s", len(raw_args), ddi_sh_path)

        return self._build_config(raw_args)

    def from_args(self, args: List[str]) -> RepackConfig:
        """Convert a list of legacy arguments directly.

        Useful when ddi.sh has already been parsed or arguments
        are passed programmatically.
        """
        raw_args = self._parse_arg_list(args)
        return self._build_config(raw_args)

    def _extract_args(self, ddi_sh_path: str) -> Dict[str, str]:
        """Extract arguments from a ddi.sh file.

        Looks for lines matching:
            /path/to/program.pl -flag value -flag2 value2
        or:
            COMMAND="/path/to/program.pl -flag value"
        """
        with open(ddi_sh_path) as f:
            content = f.read()

        # Strategy 1: Find the main command invocation line
        # Look for lines with the program path and arguments
        args: Dict[str, str] = {}

        for line in content.splitlines():
            line = line.strip()
            # Skip comments and empty lines
            if not line or line.startswith("#"):
                continue

            # Look for lines containing flag-value pairs
            # This regex finds -flag value patterns
            if re.search(r"\s-\w+\s", line):
                try:
                    tokens = shlex.split(line)
                except ValueError:
                    tokens = line.split()

                args.update(self._parse_arg_list(tokens))

        return args

    def _parse_arg_list(self, tokens: List[str]) -> Dict[str, str]:
        """Parse a list of tokens into flag-value pairs."""
        args: Dict[str, str] = {}
        i = 0
        while i < len(tokens):
            token = tokens[i]
            if token.startswith("-"):
                if token in self.BOOLEAN_FLAGS:
                    args[token] = "true"
                    i += 1
                elif i + 1 < len(tokens) and not tokens[i + 1].startswith("-"):
                    args[token] = tokens[i + 1]
                    i += 2
                else:
                    args[token] = "true"
                    i += 1
            else:
                i += 1  # skip non-flag tokens (e.g., program path)

        return args

    def _build_config(self, raw_args: Dict[str, str]) -> RepackConfig:
        """Build RepackConfig from parsed arguments."""
        config_kwargs: Dict[str, Any] = {}
        extra: Dict[str, Any] = {}
        self.gen_kits: set = set()

        for flag, value in raw_args.items():
            # Collect -gen_{kit} flags separately
            if flag.startswith(self.GEN_FLAG_PREFIX):
                kit_name = flag[len(self.GEN_FLAG_PREFIX):]
                self.gen_kits.add(kit_name)
                continue

            if flag in self.ARG_MAP:
                field = self.ARG_MAP[flag]
                config_kwargs[field] = self._transform_value(field, value)
            else:
                # Unmapped args go to extra
                extra[flag.lstrip("-")] = value

        config_kwargs["extra"] = extra

        # Auto-derive library_name from new_name + new_ver if available
        new_name = config_kwargs.get("new_name", "")
        new_ver = config_kwargs.get("new_ver", "")
        if new_name and "library_name" not in config_kwargs:
            config_kwargs["library_name"] = (
                f"{new_name}_{new_ver}" if new_ver else new_name
            )

        # Build SpecCollection from args
        specs = self._build_specs(raw_args)
        config_kwargs["specs"] = specs

        return RepackConfig(**config_kwargs)

    def _transform_value(self, field: str, value: str) -> Any:
        """Transform a raw string value to the appropriate type.

        TEMPLATE: Add field-specific transformations here.
        """
        # List fields: split comma-separated values
        if field in ("pvts", "cells"):
            return [v.strip() for v in value.split(",") if v.strip()]

        # Integer fields
        if field == "max_workers":
            return int(value)

        # Default: string
        return value

    def _build_specs(self, raw_args: Dict[str, str]) -> SpecCollection:
        """Build SpecCollection from raw arguments.

        TEMPLATE: Override this to build per-kit specs from legacy args.
        """
        # Example: create specs from relevant arguments
        specs = SpecCollection()

        # TODO: Map legacy spec-related args to per-kit specs
        # Example:
        #   if "-liberty_config" in raw_args:
        #       specs.set_kit_spec("liberty", {"config": raw_args["-liberty_config"]})

        return specs
